import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar, Context, Footer, ToastProvider } from "@/components";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dex Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className={classNames(inter.className, "bg-gray-950")} suppressHydrationWarning={true}>
        <Context>
          <ToastProvider>
            <Navbar />
            <main className="flex min-h-screen flex-col items-center justify-between py-24">
              {children}
            </main>
            <Footer />
          </ToastProvider>
        </Context>
      </body>
    </html>
  );
}
